version: '3.8'

services:


  jupyterhub:
    user: root
    build: ./app/jupyterhub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "jupyterhub-data:/data"
      - "jupyterhub-shared:/home/shared"
      - ./app/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
    environment:
      - DOCKER_NOTEBOOK_IMAGE=notebook_img
      - DOCKER_NETWORK_NAME=jupyterhub_default
      - HOST=${HOST}
      - JUPYTERHUB_IDLE_CULLER_TIMEOUT=3600
    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --debug
    labels:
      - "traefik.http.routers.jupyterhub.rule=Host(``)"
      - "traefik.http.routers.jupyterhub.entrypoints=https"
      - "traefik.http.routers.jupyterhub.tls.certresolver=tlsresolver"

  notebook-throwaway:
    build: ./app/notebook
    image: notebook_img
    container_name: notebook-throwaway
    network_mode: none
    command: echo

volumes:
  jupyterhub-data:
  jupyterhub-shared:

networks:
  default:
    name: jupyterhub_default
